let obj = JSON.parse($response.body);
obj.value.vip = true;
obj.value.defaultRecognize.defaultNormal = -100;
obj.value.defaultRecognize.defaultBatch = -100;
obj.value.defaultRecognize.defaultTranslate = -100;
obj.value.defaultRecognize.recognizeTranslateAll = 1;
obj.value.levels.monthPrice = -1;
obj.value.levels.yearPrice = -1;
obj.value.levels.recognizeNormal = 1;
obj.value.levels.recognizeTranslate = -100;
obj.value.levels.recognizeTranslateAll = 1;
$done({ body: JSON.stringify(obj) });
