let obj = JSON.parse($response.body);
obj.value.vip = true;
obj.value.recognize.remainBatch = -100;
obj.value.recognize.translateCount = 3;
obj.value.recognize.remainTranslate = -100;
obj.value.recognize.shareCount = 3;
obj.value.recognize.normalCount = -100;
obj.value.recognize.remainShare = 3;
obj.value.recognize.recognizeTranslateAll = 1;
obj.value.recognize.remainNormal = 0;
obj.value.recognize.balanceCount = -100;
obj.value.recognize.batchCount = 1;
$done({ body: JSON.stringify(obj) });