let obj = JSON.parse($response.body);
obj.value.vip = true;
obj.level.recognize;
obj.level.recognize.remainBatch = -100;
obj.level.recognize.translateCount = 3;
obj.level.recognize.remainTranslate = -100;
obj.level.recognize.shareCount = 3;
obj.level.recognize.normalCount = -100;
obj.level.recognize.remainShare = 3;
obj.level.recognize.recognizeTranslateAll = 1;
obj.level.recognize.remainNormal = 0;
obj.level.recognize.balanceCount = -100;
obj.level.recognize.batchCount = 1;
$done({ body: JSON.stringify(obj) });