let obj = JSON.parse($response.body);
obj.value.vip = true;
obj.level.id = 2;
obj.level.recognizeTranslateAll = 1;
obj.level.recognizeBatch = -100;
obj.level.seq = 2;
obj.level.recognizeTranslate = -100;
obj.level.name = "黄金会员";
obj.level.recognizeNormal = -100;
obj.value.defaultRecognize.defaultBatch = -100;
obj.value.defaultRecognize.defaultTranslate = -100;
obj.value.defaultRecognize.recognizeTranslateAll = 1;
$done({ body: JSON.stringify(obj) });